FROM nginx:alpine

# Create directory structure
WORKDIR /usr/share/nginx/html

# Copy static files
COPY static /usr/share/nginx/html/static/
COPY index.html /usr/share/nginx/html/

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]