#version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - .:/app
      - cache_data:/app/cache

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "7860:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./static:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

networks:
    default:
      external: true
      name: metrominet

volumes:
  cache_data: