#version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - .:/app
      - cache_data:/app/cache
    networks:
      - metrominet

  web:
    build: .
    ports:
      - "7860:7860"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - .:/app
    command: python frontend.py
    depends_on:
      - api
    networks:
      - metrominet

networks:
  metrominet:
    driver: bridge

volumes:
  cache_data: